analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.9119032877497375
  brandStrength: 0
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#ff1010'
    - '#1f4686'
    - '#000000'
    - '#9c9c9c'
  lightness: 0.8125
purpose: []
favicon: null
name: Devin Pike
typography_spectrum: 0.40538
