name: Devin Pike
favicon: null
layout_spectrum: 0.74184
typography_spectrum: 0.40538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ecea'
    - '#141412'
    - '#88817b'
    - '#ff6534'
    - '#aa0e16'
  brandStrength: 0.6855259679723531
  lightness: 0.4805388697423041
  saturation: 0.9119032877497375
  rhythmicContrast: 0.20504862628877163
purpose: []
