name: Devin Pike
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff1010'
    - '#1f4686'
    - '#000000'
    - '#9c9c9c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.9119032877497375
  rhythmicContrast: 0.75
purpose: []
